# fly.toml app configuration file generated for expense-tracker-bot
app = "expense-tracker-bot"
primary_region = "bom"  # Mumbai region, change as needed

[build]

[env]
  PORT = "8080"
  LOG_LEVEL = "info"
  IS_DEV_MODE = "false"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[mounts]
  source = "expense_tracker_data"
  destination = "/data"

[processes]
  app = "./expense-tracker-bot"

[deploy]
  release_command = "echo 'Deployment started'"

[experimental]
  enable_consul = false

[metrics]
  port = 9091
  path = "/metrics" 