name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy to Fly.io'
        required: true
        default: 'false'
        type: choice
        options:
          - 'false'
          - 'true'

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: expense_tracker_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...
      env:
        DATABASE_URL: postgres://postgres:password@localhost:5432/expense_tracker_test?sslmode=disable

    - name: Run linter
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest

    - name: Build application
      run: go build -o expense-tracker-bot ./cmd

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: expense-tracker-bot
        path: expense-tracker-bot

  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.deploy == 'true'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: expense-tracker-bot
        path: .

    - name: Set up Flyctl
      uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Deploy to Fly.io
      run: flyctl deploy --remote-only
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    - name: Health check
      run: |
        sleep 30
        flyctl status --app expense-tracker-bot

    - name: Notify deployment success
      run: |
        echo "✅ Deployment completed successfully!"
        echo "🌐 App URL: https://expense-tracker-bot.fly.dev"
        echo "📊 Health Check: https://expense-tracker-bot.fly.dev/health" 