name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    strategy:
      matrix:
        go-version: [1.23.x, 1.24.x]
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Verify Go version
      run: go version

    - name: Install dependencies
      run: go mod download

    - name: Run tests with race detection
      run: make test-silent

    - name: Run golangci-lint (v2)
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.1.0
        args: --verbose  

    - name: Create build directory
      run: mkdir -p build

    - name: Build application
      run: go build -o build/expense-tracker-bot ./cmd

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: expense-tracker-bot-${{ matrix.go-version }}
        path: build/
        retention-days: 7 